# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WristNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WristNews

end

target 'WristNews WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WristNews WatchKit App

end

target 'WristNews WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WristNews WatchKit Extension
  
  pod ‘Kingfisher/SwiftUI’, ‘~> 5.0’
  pod 'Alamofire', '~> 5.1'
  pod 'SwiftyJSON', '~> 4.0'

end
