# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Spotify' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Spotify
    pod 'SwiftLint'
    pod 'SDWebImage'
    pod 'Appirater'
    pod 'Firebase/Analytics'

  target 'SpotifyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
