# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Snapshot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Snapshot

  target 'SnapshotTests' do
    inherit! :search_paths
    # Pods for testing
     pod 'iOSSnapshotTestCase'
  end

  target 'SnapshotUITests' do
    # Pods for testing
  end

end
